# Generated by Django 5.2.4 on 2025-07-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('ingredients', models.CharField(max_length=255)),
                ('cooking_time', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
