# Generated by Django 5.2.4 on 2025-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='no_picture.jpg', null=True, upload_to='recipes'),
        ),
    ]
